version: '3'
services:
  app:
    build:
      context: .
    # environment:
    #   SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/bucketlist
      - public-data:/bucketlist/public
      - tmp-data:/bucketlist/tmp
      - log-data:/bucketlist/log
    depends_on:
      - db
      - webdriver_chrome
  # selenium_chrome:
  #   image: selenium/standalone-chrome-debug
  #   logging:
  #     driver: none
  # chrome:
  #   image: seleniarm/standalone-chromium
  #   ports:
  #     - "4444:4444"
  #   shm_size: 2gb
  # chromium:
  #   image: seleniarm/standalone-chromium:4.1.4-20220429
  #   volumes:
  #     - ./tmp/downloads:/bucketlist/tmp/downloads
  #   ports:
      # - 4444:4444  
  db:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  webdriver_chrome:
    image: selenium/standalone-chrome   
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/bucketlist/public
      - tmp-data:/bucketlist/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: