version: '3'
services:
  app:
    build:
      context: .
    environment:
      - DISPLAY=$DISPLAY
    # environment:
    #   SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/bucketlist
      - public-data:/bucketlist/public
      - tmp-data:/bucketlist/tmp
      - log-data:/bucketlist/log
    depends_on:
      - db
      # - firefox
  #     # - chromium
  # firefox:
  #   build: .
  #   # image: selenium/standalone-firefox:latest
  #   image: seleniarm/node-firefox:latest
  #   ports:
  #     - 4444:4444
  #   tty: true  
  #   environment:
  #     - DISPLAY=$DISPLAY
  #   volumes:
  #     - /tmp/.X11-unix/:/tmp/.X11-unix/
  # chromium:
  #   image: seleniarm/standalone-chromium:latest
  #   ports:
  #     - 4444:4444
  db:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/bucketlist/public
      - tmp-data:/bucketlist/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: